[versions]
sdk-compile = "33"
sdk-target = "33"
sdk-min = "21"

gradle-android = "7.3.1"
kotlin = "1.7.22"

kotest = "5.5.4"

[libraries]
# Android
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.9.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.5.1" }

koin = { group = "io.insert-koin", name = "koin-android", version = "3.3.0" }

kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.4.1" }


## Testing
test-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.4" }
test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.0" }

# Testing
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version = "1.13.3" }


[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.0.0" }
