name: Codestyle

on: [ push ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Provide Ktlint Results
        uses: actions/upload-artifact@v4
        with:
          name: Ktlint Results
          path: ./*/build/reports/ktlint/
