name: Detekt

on: [ push ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Provide Detekt Results
        uses: actions/upload-artifact@v4
        with:
          name: Detekt Results
          path: core/build/reports/detekt/
