name: Ktlint

on: [ push ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Provide Ktlint Results
        uses: actions/upload-artifact@v3
        with:
          name: Ktlint Results
          path: core/build/reports/ktlint/

      - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: core/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.sarif
