name: Ktlint

on: [ push ]

jobs:
  ktlint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 17
      #     cache: gradle

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Provide Ktlint Results
        uses: actions/upload-artifact@v3
        with:
          name: Ktlint Results
          path: core/build/reports/ktlint/
